default_platform(:ios)

platform :ios do
  lane :fetch_install_certs do
    cert(
      keychain_path: ENV['KEYCHAIN_PATH'],
      generate_apple_certs: "false"
    )
  end

  lane :fetch_install_provisioning do
    sigh(
      app_identifier: "org.nypl.labs.SimplyE"
    )
    sigh(
      app_identifier: "org.nypl.labs.SimplyE",
      adhoc: "true"
    )
    sigh(
      app_identifier: "org.nypl.labs.OpenEbooks"
    )
    sigh(
      app_identifier: "org.nypl.labs.OpenEbooks",
      adhoc: "true"
    )
  end
end
