name: SimplyE Build
on: workflow_dispatch
jobs:
  upload-arc:
    runs-on: macOS-latest
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Force Xcode 11.5
        run: sudo xcode-select -switch /Applications/Xcode_11.5.app
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Check Firebase Tools
        run: command -v firebase && firebase --version
      - name: Checkout main repo and submodules
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          token: ${{ secrets.IOS_DEV_CI_PAT }}
      - name: Checkout Adobe RMSDK
        uses: actions/checkout@v2.3.4
        with:
          repository: NYPL-Simplified/DRM-iOS-AdeptConnector
          token: ${{ secrets.IOS_DEV_CI_PAT }}
          path: ./DRM-iOS-AdeptConnector
      - name: Checkout Certificates
        uses: actions/checkout@v2.3.4
        with:
          repository: NYPL-Simplified/Certificates
          token: ${{ secrets.IOS_DEV_CI_PAT }}
          path: ./Certificates
      - name: Checkout NYPLAEToolkit
        uses: actions/checkout@v2.3.4
        with:
          repository: NYPL-Simplified/NYPLAEToolkit
          token: ${{ secrets.IOS_DEV_CI_PAT }}
          path: ./NYPLAEToolkit
      - name: Fetch AudioEngine
        run: ./NYPLAEToolkit/scripts/fetch-audioengine.sh
      - name: Setup iOS Distribution Details
        env:
          BUILD_CONTEXT: ci
          IOS_DISTR_IDENTITY_PASSPHRASE: ${{ secrets.IOS_DISTR_IDENTITY_PASSPHRASE }}
          IOS_DISTR_IDENTITY_BASE64: ${{ secrets.IOS_DISTR_IDENTITY }}
          FASTLANE_USER: ${{ secrets.APPLEID_USERNAME }}
          FASTLANE_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        run: ./scripts/decode-install-secrets.sh simplye
      - name: Set up repo for DRM build
        run: exec ./scripts/setup-repo-drm.sh
        env:
          BUILD_CONTEXT: ci
      - name: Build non-Carthage 3rd party dependencies
        run: ./scripts/build-3rd-party-dependencies.sh
        env:
          BUILD_CONTEXT: ci
      - name: Carthage Bootstrap
        uses: devbotsxyz/carthage-bootstrap@v1
        with:
          github-token: ${{ secrets.IOS_DEV_CI_PAT }}
          platform: iOS
          cache: false
          verbose: true
      - name: Archive SimplyE
        run: ./scripts/xcode-archive.sh simplye
        env:
          BUILD_CONTEXT: ci
      - name: Export for Ad Hoc
        run: ./scripts/xcode-export-adhoc.sh simplye
        env:
          BUILD_CONTEXT: ci
      - name: Upload to Firebase
        run: ./scripts/firebase-upload.sh simplye
        env:
          BUILD_CONTEXT: ci
          GITHUB_TOKEN: ${{ secrets.IOS_DEV_CI_PAT }}
      - name: Upload to iOS-binaries
        run: ./scripts/ios-binaries-upload.sh simplye
        env:
          BUILD_CONTEXT: ci
          GITHUB_TOKEN: ${{ secrets.IOS_DEV_CI_PAT }}
      - name: Export for App Store
        if: startsWith(github.ref, 'refs/heads/release/')
        run: ./scripts/xcode-export-appstore.sh simplye
        env:
          BUILD_CONTEXT: ci
      - name: Upload to TestFlight
        if: startsWith(github.ref, 'refs/heads/release/')
        run: ./scripts/testflight-upload.sh simplye
        env:
          BUILD_CONTEXT: ci
          IOS_DISTR_IDENTITY_PASSPHRASE: ${{ secrets.IOS_DISTR_IDENTITY_PASSPHRASE }}
          FASTLANE_USER: ${{ secrets.APPLEID_USERNAME }}
          FASTLANE_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLEID_APP_SPECIFIC_PASSWORD }}
