name: Check Build Number
on:
  push:
    branches:
#      - support/OE-161/openebooks-ci
      - develop
      - release/**
      - feature/**
jobs:
  checkbinaries:
    runs-on: macOS-latest
    steps:
      - name: Dump GitHub context
        env:
          FULL_EVENT: ${{ toJson(github.event) }}
        run: echo "FULL_EVENT=$FULL_EVENT"
      - name: Checkout main repo
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.IOS_DEV_CI_PAT }}
      - id: detectapp
        name: Detect which app to build
        run: ./scripts/detect-app-to-build.sh
        env:
          BUILD_CONTEXT: ci
          GITHUB_TOKEN: ${{ secrets.IOS_DEV_CI_PAT }}
          COMMIT_BEFORE_MERGE: ${{ github.event.before }}
    outputs:
      simplye_changed: ${{ steps.detectapp.outputs.simplye_changed }}
      openebooks_changed: ${{ steps.detectapp.outputs.openebooks_changed }}
#      - name: Check Build Number
#        run: ./scripts/ios-binaries-check.sh simplye
#        env:
#          BUILD_CONTEXT: ci
#          GITHUB_TOKEN: ${{ secrets.IOS_DEV_CI_PAT }}
#      - name: Trigger Archive+Upload
#        uses: benc-uk/workflow-dispatch@v1
#        with:
#          workflow: SimplyE and Open eBooks Build
#          token: ${{ secrets.IOS_DEV_CI_PAT }}
  upload-arc:
    runs-on: macOS-latest
    needs: checkbinaries
    steps:
      - name: TESTING SYNTAX
        run: echo ${{needs.checkbinaries.outputs.simplye_changed}} ${{needs.checkbinaries.outputs.openebooks_changed}}
      - name: Archive SimplyE
        if: needs.checkbinaries.outputs.simplye_changed == '1'
        run: echo "ARCHIVE SIMPLYE"
      - name: Archive OE
        if: needs.checkbinaries.outputs.openebooks_changed == '1'
        run: echo "ARCHIVE OE"


