name: NonDRM Build
on:
  pull_request:
jobs:
  build:
    runs-on: macOS-13
    steps:
      - name: Print System Info
        run: uname -a
      - name: Check available Xcodes
        run: ls -la /Applications | grep Xcode
      - name: Force Xcode we use for development
        run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app
      - name: Checkout main repo
        uses: actions/checkout@v4
      - name: Set up repo for nonDRM build
        run: exec ./scripts/setup-repo-nodrm.sh
        env:
          BUILD_CONTEXT: ci
      - name: Build dependencies
        run: ./scripts/build-dependencies.sh --no-private
        env:
          BUILD_CONTEXT: ci
      - name: Build SimplyE without DRM support
        run: ./scripts/xcode-build-nodrm.sh
