name: NonDRM Build
on:
  pull_request:
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Check available Xcodes
        run: ls -la /Applications
      - name: Force latest Xcode #currently 13.2.1 cos 13.3.1 still in beta at github; once ready for prod the Xcode.app symlink will automatically select it
        run: sudo xcode-select -switch /Applications/Xcode.app
      - name: Checkout main repo
        uses: actions/checkout@v2
      - name: Set up repo for nonDRM build
        run: exec ./scripts/setup-repo-nodrm.sh
        env:
          BUILD_CONTEXT: ci
      - name: Build dependencies
        run: ./scripts/build-dependencies.sh --no-private
        env:
          BUILD_CONTEXT: ci
      - name: Build SimplyE without DRM support
        run: ./scripts/xcode-build-nodrm.sh
