name: NonDRM Build
on:
  pull_request:
jobs:
  build:
    runs-on: macOS-12
    steps:
      - name: Check available Xcodes
        run: ls -la /Applications
      - name: Force Xcode 13.1
        run: sudo xcode-select -switch /Applications/Xcode_13.1.app
      - name: Checkout main repo
        uses: actions/checkout@v2
      - name: Set up repo for nonDRM build
        run: exec ./scripts/setup-repo-nodrm.sh
        env:
          BUILD_CONTEXT: ci
      - name: Build dependencies
        run: ./scripts/build-dependencies.sh --no-private
        env:
          BUILD_CONTEXT: ci
      - name: Build SimplyE without DRM support
        run: ./scripts/xcode-build-nodrm.sh
