name: Unit Tests
on:
  pull_request:
jobs:
  build-and-test:
    runs-on: macOS-11
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Force Xcode 13.1
        run: sudo xcode-select -switch /Applications/Xcode_13.1.app
      - name: Checkout main repo and submodules
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          token: ${{ secrets.IOS_DEV_CI_PAT }}
      - name: Checkout Adobe RMSDK
        uses: actions/checkout@v2.3.4
        with:
          repository: NYPL-Simplified/DRM-iOS-AdeptConnector
          token: ${{ secrets.IOS_DEV_CI_PAT }}
          path: ./DRM-iOS-AdeptConnector
      - name: Set up repo for DRM build
        run: exec ./scripts/setup-repo-drm.sh
        env:
          BUILD_CONTEXT: ci
      - name: Prepare for Carthage build
        run: ./scripts/build-dependencies.sh
        env:
          BUILD_CONTEXT: ci
          GITHUB_TOKEN: ${{ secrets.IOS_DEV_CI_PAT }}
      - name: Carthage Bootstrap
        uses: NYPL-Simplified/carthage-bootstrap@main
        with:
          github-token: ${{ secrets.IOS_DEV_CI_PAT }}
          platform: iOS
          use-xcframeworks: true
      - name: Build NYPLAEToolkit
        run: ./scripts/build-NYPLAEToolkit.sh
        env:
          GITHUB_TOKEN: ${{ secrets.IOS_DEV_CI_PAT }}
      - name: Run SimplyE tests
        run: ./scripts/xcode-test.sh simplye
        env:
          BUILD_CONTEXT: ci
      - name: Run Open eBooks tests
        run: ./scripts/xcode-test.sh openebooks
        env:
          BUILD_CONTEXT: ci
