name: Unit Tests
on:
  pull_request:
jobs:
  build-and-test:
    runs-on: macOS-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Force Xcode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      - name: Checkout main repo and submodules
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          token: ${{ secrets.IOS_DEV_CI_PAT }}
      - name: Checkout Adobe RMSDK
        uses: actions/checkout@v2.3.4
        with:
          repository: NYPL-Simplified/DRM-iOS-AdeptConnector
          token: ${{ secrets.IOS_DEV_CI_PAT }}
          path: ./DRM-iOS-AdeptConnector
      - name: Checkout Certificates
        uses: actions/checkout@v2.3.4
        with:
          repository: NYPL-Simplified/Certificates
          token: ${{ secrets.IOS_DEV_CI_PAT }}
          path: ./Certificates
      - name: Set up repo for DRM build
        run: exec ./scripts/setup-repo-drm.sh
        env:
          BUILD_CONTEXT: ci
      - name: Build non-Carthage 3rd party dependencies
        run: ./scripts/build-3rd-party-dependencies.sh
        env:
          BUILD_CONTEXT: ci
      - name: Carthage Bootstrap
        uses: devbotsxyz/carthage-bootstrap@v1
        with:
          github-token: ${{ secrets.IOS_DEV_CI_PAT }}
          platform: iOS
          cache: false
          verbose: true
      - name: Run SimplyE tests
        run: ./scripts/xcode-test.sh simplye
        env:
          BUILD_CONTEXT: ci
      - name: Run Open eBooks tests
        run: ./scripts/xcode-test.sh openebooks
        env:
          BUILD_CONTEXT: ci
