name: Unit Tests
on:
  pull_request:
jobs:
  build-and-test:
    runs-on: macOS-12
    if: github.event.pull_request.head.repo.full_name == github.repository
    env:
      GITHUB_TOKEN: ${{ secrets.IOS_DEV_CI_PAT }}
    steps:
      - name: Force Xcode 13.1
        run: sudo xcode-select -switch /Applications/Xcode_13.1.app
      - name: Print System Info
        run: uname -a
      - name: Checkout main repo and submodules
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          token: ${{ secrets.IOS_DEV_CI_PAT }}
      - name: Checkout Adobe RMSDK
        uses: actions/checkout@v2.3.4
        with:
          repository: NYPL-Simplified/DRM-iOS-AdeptConnector
          token: ${{ secrets.IOS_DEV_CI_PAT }}
          path: ./DRM-iOS-AdeptConnector
      - name: Add Private Repo Auth
        # This ensures SPM can resolve dependencies for private repos.
        # Other options included using `-usePackageSupportBuiltinSCM` (or
        # possibly `-scmProvider system`) in xcodebuild
        run: echo "GITHUB_REPO_OWNER=$GITHUB_REPO_OWNER" && git config --global --add url."https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO_OWNER}".insteadOf "https://github.com/${GITHUB_REPO_OWNER}"
        env:
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
      - name: Set up repo for DRM build
        run: exec ./scripts/setup-repo-drm.sh
        env:
          BUILD_CONTEXT: ci
      - name: Prepare for Carthage build
        run: ./scripts/build-dependencies.sh
        env:
          BUILD_CONTEXT: ci
      - name: Carthage Bootstrap
        uses: NYPL-Simplified/carthage-bootstrap@main
        with:
          github-token: ${{ secrets.IOS_DEV_CI_PAT }}
          platform: iOS
          use-xcframeworks: true
      - name: Fetch AudioEngine
        run: cd ./NYPLAEToolkit && ./scripts/fetch-audioengine.sh
      - name: Run SimplyE tests
        run: ./scripts/xcode-test.sh simplye
        env:
          BUILD_CONTEXT: ci
      - name: Run Open eBooks tests
        run: ./scripts/xcode-test.sh openebooks
        env:
          BUILD_CONTEXT: ci
